DROP TABLE IF EXISTS MEMBERS;

CREATE TABLE MEMBERS (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL,
  ALIAS_NAME VARCHAR(250) DEFAULT NULL,
  LOGIN VARCHAR(250) DEFAULT NULL,
  RATING DECIMAL DEFAULT 0.0,
  STATUS VARCHAR(10) DEFAULT 'ACTIVE',
  JOINED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);